### ISSUE TITLE
Reconsider design of filters

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-graphql#25]
Follow on from #12. Got some great tips from Bret on Twitter: https://twitter.com/binarybret/status/1291191732579827714

> Did you consider making filters part of the schema instead of strings?
> 
> A couple of examples of what I’m talking about: 
> 
> https://grandstack.io/docs/graphql-filtering/
>
> https://pypi.org/project/graphene-sqlalchemy-filter/
>
> https://realtime-location-tracking.demo.hasura.app/console

As a reminder, filters currently look like this:
```graphql
{
  repos(filters: ["license=apache-2.0", "stargazers_count__gt=10"]) {
  ...
```

**Comment by simonw** [comment]
I quite like the design proposed here: https://github.com/graphql-python/graphene-sqlalchemy/pull/164
```graphql
query {
    pets(filter: {name: {eq: "Lassie"}}) {
    ...
```
I want to support a list rather than a dictionary, but I do like the idea that each filter looks like this:
```
{name: {operator: "value"}}
```

**Comment by simonw** [comment]
So `repos(filters: ["license=apache-2.0", "stargazers_count__gt=10"])` would instead be:

```graphql
{
  repos(filters: [{license: {eq: "apache-2.0"}}, {stargazers_count: {gt: '0}}]) {
  ...
```

**Comment by simonw** [comment]
If this means I get autocomplete against column names and operators - plus compatibility with GraphQL variables for the values - this could be a worthwhile change.

**Comment by simonw** [comment]
I can't figure out how to represent a type in Graphene which looks like this:

   filters: is a list of {enum_of_column_names: {enum_of_operators: string-value}}

**Comment by simonw** [comment]
Full list of operators I would want to support: https://datasette.readthedocs.io/en/stable/json_api.html#column-filter-arguments

**Comment by simonw** [comment]
I think I know how to do this: `filters` is a list of `usersComparison` objects, where `usersComparison` is a type that has a field for each column name that has a value of type `Operation`.

The `Operation` type has a field for each of the allowed operations each matching to a value that's a string. Or maybe even a value that's dependent on the type of the column - so there would be `StringOperation` and `IntegerOperation` and `FloatOperation` types.

**Comment by simonw** [comment]
Got this working in dev:

```graphql
{
  repos(filters: [{name: {contains: "datasette"}, stargazers_count: {gt: "10"}}]) {
    nodes {
      full_name
      stargazers_count
    }
  }
}
```

**Comment by simonw** [comment]
Got this working too:

```graphql
{
  repos(filters: [{name: {in: ["datasette", "sqlite-utils"]}, stargazers_count: {gt: "10"}}]) {
    nodes {
      full_name
      stargazers_count
    }
  }
}
```

**Comment by simonw** [comment]
Managed to fix the types:

```graphql
{
  repos(filters: [{name: {in: ["datasette", "sqlite-utils"]}, stargazers_count: {gt: 10}}]) {
    nodes {
      full_name
      stargazers_count
    }
  }
}
```

**Comment by bretwalker** [comment]
This is great. I was hacking on this a little last night, but didn't quite get there. Excited to see this progress!

**Comment by simonw** [comment]
Here's the example in the test:
https://github.com/simonw/datasette-graphql/blob/87eba0c242efbc0b1096ebcc5f16cc36062de520/examples/filters.md#L1-L12

**Comment by simonw** [comment]
I'm a bit annoyed by the use of a list here. In the vast, vast majority of cases the list will only have a single item in it, especially since this is a valid way of doing an AND (provided the and is between two different columns):
 ```graphql 
 { 
     users(filters:[{score: {gt: 50}, name: {contains: "dog"}}]) { 
         nodes { 
             name 
             score 
         } 
     } 
 } 
 ```
I'm tempted to ditch the list part of this entirely.

**Comment by simonw** [comment]
The downside of this is that you won't be easily able to use two conditions on the same column - for example "name contains 'simon' and name is not equal to 'simontest'".

But even that case can be covered like so:
```graphql
{ 
    users(filters: {name: {contains: "simon", not: "simontest"}}) { 
        nodes { 
            name 
            score 
        } 
    } 
}
```
So the only thing that won't work is an AND that needs to apply the same operation to the same column more than once. I think I can live with that limitation.

**Comment by simonw** [comment]
And if it's not a list any more I can call it `filter:` instead:
```graphql
{
  repos(filter: {license: {eq: "apache-2.0"}, stargazers_count: {gt: 10}}) {
    nodes {
      full_name
      stargazers_count
      license {
        key
      }
    }
  }
}
```
