### ISSUE TITLE
Rename table_get to table_row (nouns are better than verbs in GraphQL land)

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-graphql#36]
GraphQL prefers nouns to verbs: https://twitter.com/flaximus/status/1291906337052524546

**Comment by simonw** [comment]
Or table_one?

**Comment by simonw** [comment]
Or table_row? I'm not so keen on that as "row" is more of an implementation detail.

**Comment by simonw** [comment]
But `table_row` is list characters than `table_first`.

**Comment by simonw** [comment]
Options (using `repos` as an example table):

- `repos_get` - it's a verb, nouns are better
- `repos_one` - sure it returns just one result, but which one?
- `repos_first` - clear that it returns the first result, but a little verbose
- `repos_row` - it returns just one row
- `repos_single` - verbose, `first` is one less letter

**Comment by simonw** [comment]
Of these options, `repos_one` and `repos_row` are both noun-based and only three letters.

**Comment by aviflax** [comment]
What about `_record` or `_rec` ?

**Comment by aviflax** [comment]
FWIW, I still like `row` best, but apart from that, I like `rec` or `record` more than `one`

**Comment by simonw** [comment]
Another option: `_by`

Tools like https://www.graphile.org/postgraphile/examples/ set up fields called `forumBySlug` - the current `table_get` method is essentially `tableByPk` but with more options:

```graphql
{
  users_by(id: 12345) {
    name
  }
}
```
It would still support `filter:` and `where:` and `search:` - e.g.:


```graphql
{
  by_search: users_by(search: "simon") {
    name
  }
  by_search: users_by(filter: {name: {eq: "simon"}}) {
    name
  }  
}
```

**Comment by simonw** [comment]
The problem with `_by` for single lookups is that it would also work as a name for the `users` field (which lets you filter users by criteria, but returns more than one result). So I don't like that option.

**Comment by simonw** [comment]
I'm coming round to `_row` a bit more now.

**Comment by simonw** [comment]
I'm going with `_row`.

**Comment by simonw** [comment]
A bunch of demo queries in https://github.com/simonw/datasette-graphql/blob/006238a7527ee3d7bc0e465d613ef36f6e062dd3/examples/table_row.md

**Comment by simonw** [comment]
That query in the live demo: I'm happy with this change. Thanks, @aviflax!

https://datasette-graphql-demo.datasette.io/graphql/fixtures?query=%7B%0A%20%20table_with_rowid_row(rowid%3A%201)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%20%20table_with_pk_row(pk%3A%201)%20%7B%0A%20%20%20%20pk%0A%20%20%20%20name%0A%20%20%7D%0A%20%20table_with_compound_pk_row(pk1%3A1%2C%20pk2%3A3)%20%7B%0A%20%20%20%20name%0A%20%20%20%20pk1%0A%20%20%20%20pk2%0A%20%20%7D%0A%20%20users_row(id%3A%2012345)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D

**Comment by aviflax** [comment]
My pleasure, looks great!
