### ISSUE TITLE
Plugin hook to allow other plugins to define GraphQL APIs

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-graphql#69]
> Bonus idea: if https://github.com/simonw/datasette-graphql provided its own plugin hook then plugins like this one could expose a GraphQL API as well.

_Originally posted by @simonw in https://github.com/simonw/datasette-ripgrep/issues/18#issuecomment-737847561_

**Comment by simonw** [comment]
```python
from datasette_graphql import hookimpl

def extra_fields(datasette):
    return [
        ("hello", graphene.String(), lambda root, info: "Hello world"),
    ]
```

Returns a name, a field type and a resolve function - these are then added to the query at the root of the Schema.

**Comment by simonw** [comment]
Would use the same `async def inner()` pattern as other hooks.

**Comment by simonw** [comment]
Open question: what if the name from a plugin collides with the name of a SQLite table?

Could solve that by automatically renaming the GraphQL field for that table.

**Comment by markhalonen** [comment]
The Postgraphile project handles many of the same types of issues, you may want to look there for inspiration. It has awesome plugins

**Comment by simonw** [comment]
I proved in https://github.com/simonw/datasette-low-disk-space-hook that you can add new plugin hooks as part of another plugin, see also this TIL: https://til.simonwillison.net/datasette/register-new-plugin-hooks

**Comment by simonw** [comment]
I'm going to experiment with this hook using https://datasette.io/plugins/datasette-packages since it's a really simple plugin (much simpler than `datasette-ripgrep`).

**Comment by simonw** [comment]
Here's the hookspec:
```python
from pluggy import HookspecMarker

hookspec = HookspecMarker("datasette")


@hookspec
def graphql_extra_fields(datasette):
    "A list of (name, field_type) tuples to include in the GraphQL schema"
```
And an example plugin implementation:
```python
@hookimpl
def graphql_extra_fields():
    class Package(graphene.ObjectType):
        name = graphene.String()
        version = graphene.String()

    return [
        (
            "packages",
            graphene.Field(
                graphene.List(Package),
                description="List of installed packages",
                resolver=lambda root, info: [
                {"name": d.project_name, "version": d.version}
                for d in sorted(
                    pkg_resources.working_set, key=lambda d: d.project_name.lower()
                )
            ])
        ),
    ]
```

**Comment by simonw** [comment]
Documentation: https://github.com/simonw/datasette-graphql/blob/860e27c9c628b2e052007f8fc1bf85263173340e/README.md#adding-custom-fields-with-plugins

**Comment by simonw** [comment]
Demo: https://latest-with-plugins.datasette.io/graphql?query=%7B%0A%20%20%20%20packages%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20version%0A%20%20%20%20%7D%0A%7D
