### ISSUE TITLE
KeyError / status 500 for table with references

### ISSUE THREAD

**Issue by curiousleo** [simonw/datasette-graphql#79]
# Error message

```
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.9/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.9/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.9/site-packages/graphene/types/field.py", line 119, in type
    return get_type(self._type)
  File "/usr/local/lib/python3.9/site-packages/graphene/types/utils.py", line 45, in get_type
    return _type()
  File "/usr/local/lib/python3.9/site-packages/datasette_graphql/utils.py", line 624, in getter
    return table_classes[table]
KeyError: 'Katalogwerte'
INFO:     172.17.0.1:43848 - "GET /Marktstammdatenregister/EinheitenSolar HTTP/1.1" 500 Internal Server Error
```

Full stack trace: [traceback.txt](https://github.com/simonw/datasette-graphql/files/7360567/traceback.txt)

# SQL schema

This happens when I try to open the page of a table "EinheitenSolar". It relates to the table "Katalogwerte" (mentioned in the traceback) in that the "EinheitenSolar" table contains columns which _reference_ "Katalogwerte":

```sql
create table 'EinheitenSolar' (
  -- [...]
  'Land' integer not null references Katalogwerte(Id) deferrable initially deferred,
  'Bundesland' integer references Katalogwerte(Id) deferrable initially deferred,
  -- [...]
```

Note that without the GraphQL plugin, Datasette recognises the `references` declarations and displays the `label_column` as expected. So the tables themselves seem to have a structure that Datasette can generally work with, it's just this plugin that is unhappy.

Full SQL for "EinheitenSolar": [EinheitenSolar.sql.txt](https://github.com/simonw/datasette-graphql/files/7360568/EinheitenSolar.sql.txt)

# Screenshot

![image](https://user-images.githubusercontent.com/697092/137639348-2bb46a75-ff4e-4777-a936-8b4507cf5dca.png)

# Versions

```
$ pip list | grep -E 'datasette(-graphql)?\s'
datasette                 0.58.1
datasette-graphql         1.5
```

**Comment by simonw** [comment]
Thanks for the SQL file. I could replicate this bug locally like so:

```bash
wget https://github.com/simonw/datasette-graphql/files/7360568/EinheitenSolar.sql.txt
sqlite3 einheit.db < EinheitenSolar.sql.txt
datasette einheit.db
```

**Comment by simonw** [comment]
OK, I see what is happening here. There's only one table in that file, but it's `CREATE TABLE` refers to other tables which don't currently exist.

I'm a little surprised that Datasette doesn't throw errors there to be honest - good that it doesn't!

I think I can fix this in the `introspect_tables()` function:

https://github.com/simonw/datasette-graphql/blob/0b107eb95fca2ad0d1a15d83786c2b50313b8655/datasette_graphql/utils.py#L653-L680
