### ISSUE TITLE
Customize path for GraphiQL interface

### ISSUE THREAD

**Issue by bbbbbrie** [simonw/datasette-graphql#92]
Hello! I love this plugin!

The docs say:

> This plugin sets up /graphql as a GraphQL endpoint for the first attached database.

I’m curious: is it possible to customize the /graphql path? I couldn’t find anything about this in the docs. I’m curious if you have recommendations on how to best to this.

Thank you!

—
Brie 🦄🌈

**Comment by simonw** [comment]
This is a good idea - I need this for https://til.simonwillison.net/ too.

**Comment by simonw** [comment]
I'll do this using a metadata setting like so:
```json
{
  "plugins": {
    "datasette-graphql": {
      "path": "/-/graphql"
    }
  }
}
```

**Comment by simonw** [comment]
Here's a demo of it working: https://til.simonwillison.net/-/graphql - configured by https://til.simonwillison.net/-/metadata

**Comment by bbbbbrie** [comment]
Yay! 🎉  I have this working on my end, too. 

Thank you very much, Simon! 🙏
